### ISSUE TITLE
Eager and Lazy Loading

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#39]
Unless I'm wrong, I was pleasantly surprised to see that queries are eager loaded and thus avoids N+1 query problem. I didn't find this being documented. Is this correct or I'm just stupid?

If the queries are in fact eagerly loaded, is there a way to make them lazily loaded?

**Comment by vincentlauvlwj** [comment]
As what we discussed at issue #28, Ktorm provides a `references` function to support one-to-one and many-to-one relationships. If we use `references` to bind a column to another table, then SQLs with `left join` clauses will be generated, so that the referenced entity objects will be eagerly loaded when we are querying the tables.

Documents can be found here [Table.references](https://ktorm.liuwj.me/api-docs/me.liuwj.ktorm.schema/-table/references.html) and here [Column Binding](https://ktorm.liuwj.me/en/entities-and-column-binding.html#Column-Binding).

And if you need the lazy loading behavior, you can implement it by a property with a custom getter, for example: 

```kotlin
interface Employee : Entity<Employee> {
    companion object : Entity.Factory<Employee>()
    var id: Int
    var name: String
    var job: String
    var manager: Employee?
    var hireDate: LocalDate
    var salary: Long

    var departmentId: Int

    val department: Department get() {
        var dept = this["department"]
        if (dept == null) {
            dept = Departments.findById(departmentId) ?: error("department not found")
            this["department"] = dept
        }

        return dept as Department
    }
}

object Employees : Table<Employee>("t_employee") {
    val id by int("id").primaryKey().bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
    val job by varchar("job").bindTo { it.job }
    val managerId by int("manager_id").bindTo { it.manager?.id }
    val hireDate by date("hire_date").bindTo { it.hireDate }
    val salary by long("salary").bindTo { it.salary }
    val departmentId by int("department_id").bindTo { it.departmentId }
}
```
