### ISSUE TITLE
Funny incident (not an issue) with multiple primary keys.

### ISSUE THREAD

**Issue by AxelG1** [vincentlauvlwj/Ktorm#66]
A few weeks ago, I implemented a service. Some tables had composite primary keys in SQL. I remember being astounded that this is implicitly supported when doing the Ktorm mapping.

Today I started integrating the service, but in the meantime, primary key uniqueness is checked (it is commit 2d341f1eaeca3a7e7588c8c5df862a3815014e81)! 

I wonder why it worked just as expected before...  maybe because I didn't use lookups by ID, but employed regular where clauses.

Have you already thought of how to realize compound/composite keys? I shall have a look, how other ORMs do it...

**Comment by vincentlauvlwj** [comment]
This is because at the start of the project, in order to build a prototype as soon as possible, I decided not to support composite primary keys temporarily, which can make the code simpler and help me to stay focus on the most important features. 

But later I found that although we don't support composite primary keys, we can still call the `primaryKey()`  on multiple fields in a table object. If we did this, the primary key would be the column lastly called `primaryKey()`. That might lead to some misunderstandings to users, so I added the check to the code (commit 2d341f1).

By now, Ktorm is being more stable, we should indeed start considering to support compisite primary keys.

**Comment by vincentlauvlwj** [comment]
Added in version 3.0.0

**Comment by hendraanggrian** [comment]
Pardon me, I still encounter compound primary key issue.

```
Caused by: java.lang.IllegalStateException: Cannot reference the table Stations because it has compound primary keys.
	at me.liuwj.ktorm.schema.BaseTable.checkReferencePrimaryKey(BaseTable.kt:245)
	at me.liuwj.ktorm.schema.BaseTable.doBindInternal(BaseTable.kt:204)
	at com.example.dao.Trips.<clinit>(Trip.kt:125)
	... 10 more
Exception running application com.example.App
```

I tried this with version 3.0.0 and 3.6.0.
