### ISSUE TITLE
insertAndGenerateKeys() fails on Android with SQLDroid

### ISSUE THREAD

**Issue by clydebarrow** [vincentlauvlwj/Ktorm#76]
I'm trying to use Ktorm on Android. Reading an existing database works fine with SQLDroid, but when I come to create records the function `BaseTable#insertAndGenerateKey()` fails with a null pointer error. The problem is that it results in a call to `conn.prepareStatement(sql, RETURN_GENERATED_KEYS)` which is not supported by SQLDroid.

**Comment by vincentlauvlwj** [comment]
Thanks for your feedback, but this seems to be an issue of SQLDroid, because SQLDroid dosen't supports the method `SQLDroidConnection.prepareStatement(String sql, int autoGeneratedKeys)` and returns null.

I noticed that this issue has been fixed by them ([7ac1535](https://github.com/SQLDroid/SQLDroid/commit/7ac1535962ec41680ba7dd65b71b6be9818bde0c#diff-bebbead4a3a5f8998c8e4b48119901ceR321)), so you just need to upgrade to version `1.1.0-rc1`.

```groovy
compile 'org.sqldroid:sqldroid:1.1.0-rc1'
```

**Comment by vincentlauvlwj** [comment]
Also thank you for your PR. I will read your code carefully. But I'm not sure that if it is appropriate to do this workaround in Ktorm just because of a SQLDroid issue which is already fixed.

**Comment by clydebarrow** [comment]
That's good to know about SQLDroid, but it's not the only target. The Robovm SQLite driver also has the same limitations, so I need the PR for that plaform anyway.

**Comment by vincentlauvlwj** [comment]
Published in Ktorm 2.7
